services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.server
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3001:80"
    depends_on:
      - api
