services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - type: volume
        source: db-data
        target: /app/data
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3001:80"
    depends_on:
      - api

volumes:
  db-data:
