FROM node:16-alpine as build-step
WORKDIR /app
ENV PATH /app/node_modulels/.bin:$PATH
COPY fe/package.json fe/package-lock.json ./
COPY ./fe/src ./src
COPY ./fe/public ./public
RUN npm install
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY deploy/nginx.default.conf /etc/nginx/conf.d/default.conf
